Repository cachix/devenv, pull requests merged in 2024-06, with the labels that each got.

#1254 Allow follows in top-level inputs and validate flake inputs
  devenv/src/config.rs
  devenv/src/main.rs
Labels: bug

#1261 devenv: resolve cli arg conflicts
  devenv/src/main.rs
Labels: cli

#1268 info: print the script description and path in `devenv info`
  devenv.nix
  src/modules/scripts.nix
Labels: enhancement

#1263 devenv: split out library
  Cargo.lock
  Cargo.toml
  devenv-run-tests/Cargo.toml
  devenv-run-tests/src/main.rs
  devenv/Cargo.toml
  devenv/src/cli.rs
  devenv/src/command.rs
  devenv/src/config.rs
  devenv/src/devenv.rs
  devenv/src/lib.rs
  devenv/src/main.rs
  package.nix
Labels: cli

#1275 process-compose: fix an error when disabling the tui
  src/modules/process-managers/process-compose.nix
Labels: bug

#1284 devenv-run-tests: override the devenv input
  devenv-run-tests/src/main.rs
Labels: bug

#1243 trafficserver: new module
  examples/trafficserver/.test.sh
  examples/trafficserver/devenv.nix
  src/modules/services/trafficserver/default.nix
  src/modules/services/trafficserver/ip_allow.json
  src/modules/services/trafficserver/logging.json
  src/modules/services/trafficserver/update.sh
Labels: module
