Repository cachix/devenv, pull requests merged in 2024-05, with the labels that each got.

#1175 rust: ensure rust can be disabled when using non-default channel
  src/modules/languages/rust.nix
Labels: bug

#1196 devenv: make common CLI options global
  devenv/src/main.rs
Labels: cli

#1213 Fix instructions for usage with flakes
  docs/guides/using-with-flakes.md
Labels: documentation

#1221 examples: rename `process_ready` to `process_healthy`
  examples/process-compose/devenv.nix
  examples/python-django/devenv.nix
Labels: documentation

#1220 opentelemetry-collector: init
  examples/opentelemetry-collector/.test.sh
  examples/opentelemetry-collector/devenv.nix
  src/modules/services/opentelemetry-collector.nix
Labels: enhancement, module

#1224 rust: assert that targets are not used with nixpkgs channel
  src/modules/languages/rust.nix
Labels: bug

#1226 dotenv: support export declarations in .env files
  src/modules/integrations/dotenv.nix
  tests/dotenv/.setup.sh
  tests/dotenv/.test.sh
Labels: bug

#1157 Reuse `DEVENV_RUNTIME` to work around `nix develop` modifying `TMPDIR`
  src/modules/top-level.nix
Labels: bug

#1232 container: override tmpdir and runtime dir
  src/modules/containers.nix
Labels: bug, containers

#1247 docs: commit docs in CI and make doc generation idempotent
  .github/workflows/generate.yml
  devenv.nix
  src/modules/integrations/hostctl.nix
  src/modules/languages/php.nix
  src/modules/languages/python.nix
  src/modules/languages/rust.nix
  src/modules/processes.nix
  src/modules/services/caddy.nix
  src/modules/services/couchdb.nix
Labels: documentation
