Repository cachix/devenv, pull requests merged in 2024-08, with the labels that each got.

#1356 Remove darwinFlags in rust module
  examples/rust-wasm-cross/devenv.nix
  examples/rust/.test.sh
  src/modules/languages/rust.nix
Labels: macos

#1366 fix: don't delete runtime dir on process down
  src/modules/processes.nix
Labels: bug

#1379 feat: add a `--quiet` flag to disable logging
  devenv/src/cli.rs
  devenv/src/devenv.rs
  devenv/src/log.rs
  devenv/src/main.rs
Labels: enhancement, cli

#1404 process-compose: fix running processes with `is_elevated`
  src/modules/process-managers/process-compose.nix
Labels: bug
