Repository cachix/devenv, pull requests merged in 2024-09, with the labels that each got.

#1410 fix: Navigation bar dissappearing
  docs/.pages
  docs/editor-support/.pages
  docs/guides/.pages
  docs/integrations/.pages
Labels: documentation

#1424 docs: fix container option descriptions
  .github/workflows/generate.yml
  docs/reference/options.md
  src/modules/containers.nix
Labels: bug, documentation

#1452 redis: prevent infinite recursion when port is set to an env var
  src/modules/services/redis.nix
Labels: bug

#1478 docs: lock requirements
  mkdocs.yml
  requirements.in
  requirements.txt
Labels: documentation

#1477 devenv: escape shell vars in task exports
  devenv/src/tasks.rs
Labels: bug, cli

#1484 fix: add missing task option descriptions
  docs/reference/options.md
  src/modules/tasks.nix
Labels: bug, documentation

#1485 fix: ignore option eval warnings in client and enforce them in ci
  devenv/src/flake.tmpl.nix
  flake.nix
Labels: bug
