Repository cachix/devenv, pull requests merged in 2025-08, with the labels that each got.

#2064 docs: add rust guide
  docs/individual-docs/languages/rust.md
  docs/supported-languages/rust.md
Labels: documentation

#2070 devenv: configure Nix to use the Cachix auth token
  devenv/src/nix.rs
Labels: cli

#2073 rust: drop `-iframework` flag on darwin
  src/modules/languages/rust.nix
Labels: bug

#2086 devenv: implement `permittedUnfreePackages`
  devenv/src/config.rs
  devenv/src/flake.tmpl.nix
  docs/devenv.schema.json
  docs/reference/yaml-options.md
  tests/permitted-unfree/devenv.nix
  tests/permitted-unfree/devenv.yaml
Labels: enhancement, cli

#2093 nix: fix several regressions
  devenv.lock
  flake.lock
Labels: bug, nix

#2100 direnv: pass `DEVENV_CMDLINE` to the shell
  devenv/direnvrc
  devenv/init/.envrc
  devenv/src/main.rs
  tests/direnv/.test.sh
Labels: bug

#2102 Fix rubyVersionFile example
  src/modules/languages/ruby.nix
Labels: documentation

#2067 flakes: reload shell on `up`/`test` and remove the need for separate packages
  docs/guides/using-with-flakes.md
  examples/simple/.envrc
  flake-module.nix
  flake.nix
  src/devenv-devShell.nix
  src/modules/flake-compat.nix
  src/modules/top-level.nix
  templates/flake-parts/.envrc
  templates/simple/.envrc
  templates/simple/flake.nix
  templates/terraform/.envrc
Labels: flakes

#2111 tasks: add json extension and a prefix to the task output file
  devenv-tasks/src/task_state.rs
Labels: tasks
