Repository cachix/devenv, pull requests merged in 2025-09, with the labels that each got.

#2133 scripts: fix the `packages` option
  examples/scripts/devenv.nix
  src/modules/scripts.nix
Labels: bug

#2158 process-compose: fix overriding per-process options
  docs/reference/options.md
  docs/supported-services/opentelemetry-collector.md
  src/modules/process-managers/process-compose.nix
  src/modules/processes.nix
  src/modules/services/opentelemetry-collector.nix
Labels: bug

#2162 process-compose: check the socket for liveness before attaching
  src/modules/process-managers/process-compose.nix
Labels: bug

#1625 Add documentation on how to enable compilation of binary dependencies.
  docs/common-patterns.md
Labels: documentation

#2167 Add Helm language support
  docs/individual-docs/languages/helm.md
  docs/reference/options.md
  docs/snippets/languages-all.md
  docs/supported-languages/helm.md
  examples/helm/.test.sh
  examples/helm/devenv.nix
  examples/supported-languages/devenv.nix
  src/modules/languages/helm.nix
Labels: enhancement, module

#2189 flake-compat: wire up and expose tasks in the devenv flake wrapper
  src/modules/flake-compat.nix
Labels: enhancement, flakes, tasks

#2175 tasks: support running in an elevated shell
  devenv-tasks/Cargo.toml
  devenv-tasks/src/config.rs
  devenv-tasks/src/lib.rs
  devenv-tasks/src/main.rs
  devenv-tasks/src/privileges.rs
  devenv-tasks/src/task_state.rs
  devenv-tasks/src/tasks.rs
  devenv/src/devenv.rs
  src/modules/process-managers/process-compose.nix
  src/modules/processes.nix
  src/modules/tasks.nix
Labels: tasks
